name: Deploy gh-pages
on:
      push:
            branches:
                  - main
jobs:
      build-and-deploy:
            runs-on: ubuntu-20.04
            steps:
                  - name: Checkout
                    uses: actions/checkout@master

                  - name: Get npm cache
                    id: cache
                    uses: actions/cache@v2
                    with:
                          path: node_modules
                          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                          restore-keys: |
                                ${{ runner.os }}-node-

                  - name: Install
                    if: steps.cache.outputs.cache-hit != 'true'
                    run: npm install

                  - name: Build
                    run: npm run build

                  - name: Deploy
                    uses: peaceiris/actions-gh-pages@v3
                    with:
                          username: Tmakerchima
                          password: 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
                          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                          personal_token: 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
                          publish_dir: ./dist
                          external_repository: Tmakerchima/gallery
                        
